"""empty message

Revision ID: 4e84cc852036
Revises: 
Create Date: 2024-12-26 09:21:44.847513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e84cc852036'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_name', sa.String(length=100), nullable=False),
    sa.Column('mach', sa.Boolean(), nullable=True),
    sa.Column('agch', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['show_name'], ['dogs.show_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))
        batch_op.alter_column('place',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.alter_column('place',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('deleted')

    op.drop_table('titles')
    op.drop_table('owner')
    # ### end Alembic commands ###
