"""events

Revision ID: bd3b02a1c3c1
Revises: 576dd824e512
Create Date: 2025-03-12 23:00:47.900216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd3b02a1c3c1'
down_revision = '576dd824e512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('runs')
    op.drop_table('owners')
    op.drop_table('titles')
    op.drop_table('dogs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dogs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('show_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('points', sa.INTEGER(), nullable=True),
    sa.Column('owner', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('show_name')
    )
    op.create_table('titles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('show_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('mach', sa.BOOLEAN(), nullable=True),
    sa.Column('agch', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['show_name'], ['dogs.show_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owners',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('pet_id', sa.INTEGER(), nullable=False),
    sa.Column('show_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('run_time', sa.FLOAT(), nullable=False),
    sa.Column('course_time', sa.FLOAT(), nullable=False),
    sa.Column('qualification', sa.BOOLEAN(), nullable=False),
    sa.Column('points', sa.INTEGER(), nullable=False),
    sa.Column('handler', sa.VARCHAR(length=50), nullable=False),
    sa.Column('trial', sa.VARCHAR(length=100), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('height', sa.VARCHAR(length=8), nullable=False),
    sa.Column('place', sa.VARCHAR(length=20), nullable=False),
    sa.Column('judge', sa.VARCHAR(length=50), nullable=False),
    sa.Column('run_class', sa.VARCHAR(length=10), nullable=False),
    sa.Column('deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['show_name'], ['dogs.show_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=False),
    sa.Column('oauth_provider', sa.VARCHAR(length=20), nullable=True),
    sa.Column('oauth_id', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=False),
    sa.Column('location_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), nullable=False),
    sa.Column('state', sa.VARCHAR(length=2), nullable=False),
    sa.Column('zipcode', sa.VARCHAR(length=10), nullable=False),
    sa.Column('club_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('website', sa.VARCHAR(length=500), nullable=True),
    sa.Column('entry_fee', sa.FLOAT(), nullable=True),
    sa.Column('closing_date', sa.DATETIME(), nullable=True),
    sa.Column('judge_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('classes_offered', sa.VARCHAR(length=500), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
